# Generated by Django 4.0.6 on 2022-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, null=True)),
                ('optionA', models.CharField(max_length=200, null=True)),
                ('optionB', models.CharField(max_length=200, null=True)),
                ('optionC', models.CharField(max_length=200, null=True)),
                ('optionD', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
