# Generated by Django 4.0.6 on 2022-07-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_rename_question_text_questionmodel_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='optionA',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='optionB',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='optionC',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='optionD',
            new_name='D',
        ),
    ]
